[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs-cli run --chip RP2040"
#runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"
rustflags = ["-Clink-args=-Map=memory.map"]

[env]
DEFMT_LOG = "debug"
